pipeline {
    agent any
    tools {
         maven 'Maven 3.3.9'
         jdk 'jdk8'
     
         }

    options {
        skipStagesAfterUnstable()
    }
    stages {
       stage('Build') {
            steps {
                sh 'echo "Building... (Test)'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh 'echo "Test success !!!!!"' 
            }
        }
    }
}